sudo: required
services:
 - docker

before_install:
 - docker build -t mklie/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true mklie/react-test npm test -- --coverage

after_success:
 - docker build -t mklie/multi-client ./client
 - docker build -t mklie/multi-nginx ./nginx
 - docker build -t mklie/multi-server ./server
 - docker build -t mklie/multi-worker ./worker
# Log in to the docker CLI
 - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
# Take images and push to docker hub
 - docker push mklie/multi-client
 - docker push mklie/multi-nginx
 - docker push mklie/multi-server
 - docker push mklie/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-142046766934'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
